# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/Fl-pailler_fpga/Fl-pailler_fpga/solution1/impl/verilog/paillier_fl_kernel.xdc

# Block Designs: bd/bd_0/bd_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0 || ORIG_REF_NAME==bd_0} -quiet] -quiet

# IP: bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0_hls_inst_0 || ORIG_REF_NAME==bd_0_hls_inst_0} -quiet] -quiet

# XDC: f:/Fl-pailler_fpga/Fl-pailler_fpga/solution1/impl/verilog/project.gen/sources_1/bd/bd_0/bd_0_ooc.xdc
