
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xpaillier_fl_kernel.h"

/*
* The configuration table for devices
*/

XPaillier_fl_kernel_Config XPaillier_fl_kernel_ConfigTable[XPAR_XPAILLIER_FL_KERNEL_NUM_INSTANCES] =
{
	{
		XPAR_PAILLIER_FL_KERNEL_0_DEVICE_ID,
		XPAR_PAILLIER_FL_KERNEL_0_S_AXI_CONTROL_BASEADDR
	}
};


